### ISSUE TITLE
Seemingly broken for SRCDS x86-64 linux branch (Ubuntu 20.04)

### ISSUE THREAD

**Issue by Fasteroid** [Metastruct/gm_enginespew#1] opened 2022-01-18 23:53 UTC
I'm trying to get EPOE working on my new x64 linux server, and have tried about everything I can think of:

- Using the 32 bit modules like an idiot
- Compiling for x86-64 using [these](https://github.com/Metastruct/gm_enginespew#building-the-project-for-linuxmacos) instructions under WSL2, then copying the binaries over to the physical linux machine.
- Compiling for x86-64 as before, but on the physical linux machine.

I've been chatting with @Oppossome over discord since she's the only friend I have from metastruct, and she suggested requiring the module through console to see what error it throws:
```
lua_run require('enginespew')
> require('enginespew')...

[ERROR] lua_run:1: Couldn't find function in library! (/home/fasteroid/Desktop/E2BI/garrysmod/lua/bin/gmsv_enginespew_linux64.dll: undefined symbol: gmod13_open)
  1. require - [C]:-1
   2. unknown - lua_run:1
```
EPOE load fine, but the x64 linux module has some issues.
I have pretty much no experience in this domain, so assistance would be greatly appreciated.

**Comment by danielga** [comment] 2022-01-19 00:02
Thought it was my version of the module 😂 
@Earu your time to shine.

**Comment by Earu** [comment] 2022-01-19 07:36
Okay so admittedly I haven't tested the x64 version on a Linux distro, it looks like the platform definitions aren't working for you and it can't find what it should do when required in gmod. @danielga are there any chances that ARCHITECTURE_IS_X86_64 is missing something for this x64 distro?

**Comment by Earu** [comment] 2022-01-19 19:26
@Fasteroid could you try to follow the compile instructions again, and tell me if it compiles now? I want to make sure that you at least are compiling for one of the branches of gmod.

If it fails with `Not x86 or x64 ?????` then we'll probably have to look into improving the platform definitions in [garrysmod_common](https://github.com/danielga/garrysmod_common)

**Comment by Fasteroid** [comment] 2022-01-20 18:34
Tried building in both WSL2 and my server box, both threw no errors during the build process, but still throw `undefined symbol: gmod13_open` when required.

**Comment by Earu** [comment] 2022-01-21 08:54
<del>You did get the last version right? If that's the case there's something you're doing wrong when compiling.</del>
<del>- Make sure you have the last version of [garrysmod_common](https://github.com/danielga/garrysmod_common) on the branch ***`x86-64-support-sourcesdk`***. </del>
<del>- Make sure you have the last version of [premake5](https://premake.github.io/download).</del>
<del>- Make sure the `premake5.lua` file in your local copy of enginespew is set to `PROJECT_GENERATOR_VERSION = 3`</del>

<del>If after checking these things it still does not work out for you then I'm afraid we can't do much more as the issue is most definitely compiling-related.</del>

**Comment by Earu** [comment] 2022-01-21 10:21
Had another person follow build steps on a linux distro for x64, the compiled bin was also missing the `gmod13_open` symbol, @danielga I'm not sure what's happening here, feels like there is some platform related issues for compiling under linux?

**Comment by danielga** [comment] 2022-01-21 11:11
The problem is that you're using the wrong name for the `source` directory. You even have `source` in the premake5 config file for the `includedirs`, yet named it `src`.

**Comment by Earu** [comment] 2022-01-21 11:17
Well this is embarassing... I don't know how I did not spot that before, either way... Fixed in https://github.com/Metastruct/gm_enginespew/commit/6b4a61df01a8f73ce86112903a9a69143c4adf5c

It should work now

**Comment by Fasteroid** [comment] 2022-01-29 19:42
I left my apartment to engineer something at my house and am currently snowed in, with no SSH keys to my server box.  I'll test this as soon as I can return.

**Comment by Fasteroid** [comment] 2022-02-01 04:52
Compiling throws an error now:
```
==== Building gmsv_enginespew (releasewithsymbols_x86_64) ====
main.cpp
../../../src/main.cpp:8:10: fatal error: Color.h: No such file or directory
 #include <Color.h>
          ^~~~~~~~~
compilation terminated.
gmsv_enginespew.make:237: recipe for target 'x86_64/ReleaseWithSymbols/intermediate/gmsv_enginespew/main.o' failed
```
I tried commenting out `#include <Color.h>` however, and while there are compiler warnings, everything _seems_ to function correctly.

**Comment by Fasteroid** [comment] 2022-02-14 23:25
@Earu oh no, the worst possible thing just happened, it seems we now segfault whenever trying to change maps in any way after starting the server.  I checked all binary modules on the server and this was the one that was causing it.  Not sure why it would be enginespew of all things and not say, vrmod, but here we are.
```
map gm_flatgrass
CWorkThreadPool::~CWorkThreadPool: work complete queue not empty, 1 items discarded.
Error loading cfg/trusted_keys_base.txt
Segmentation fault (core dumped)
cat: hlds.2625765.pid: No such file or directory
```
[crashdump.zip](https://github.com/Metastruct/gm_enginespew/files/8064591/crashdumps.zip)
Hopefully this crash information helps.  I have no idea how to debug this sort of thing.

**Comment by Earu** [comment] 2022-02-15 08:03
Pretty sure the issue was linked to the listener being deleted when the module was getting closed on map changes. Can you try to re-compile with the latest changes and tell me if you still have the issue? https://github.com/Metastruct/gm_enginespew/commit/71c3286175196288996a3a32bed5f53f6d7240fb

**Comment by Fasteroid** [comment] 2022-02-15 16:09
Nope, still segfaults on changelevel.  Also still missing `<tchar.h>` and `<Color.h>`.
Is there a way to compile this in debug mode so I can see where the segfault happens?

**Comment by Fasteroid** [comment] 2022-02-15 18:39
Seems this has been a problem before...
https://github.com/Metastruct/EPOE/commit/b1ca650edbe7d4239fd87d201927c6a5e142ec21

**Comment by Fasteroid** [comment] 2022-02-16 09:01
I did a heavy amount of investigating with my friend @Kitsumi and it appears the issue is literally just caused by having a logger present before a map change.  Might be something to do with it not liking being unloaded but we need to do more testing.

~~Seems like this may be a Garry problem (big surprise!)
https://github.com/Facepunch/garrysmod-issues/issues/5167~~

~~I'll probably re-open this later, but for now I'm closing it since there's nothing we can do about it.~~

**Comment by Fasteroid** [comment] 2022-02-16 09:04
Whoops, looks like mentioning the FP issue shows the status of this one on that thread.  Should probably leave this open.

**Comment by Kitsumi** [comment] 2022-02-16 15:52
Should be fixed by https://github.com/Metastruct/gm_enginespew/pull/2

**Comment by Fasteroid** [comment] 2022-02-16 15:54
YAHH LET'S GOO

**Comment by Fasteroid** [comment] 2022-02-16 16:20
Confirmed working on my production server.  Let's close this once and for all.
[EDIT] Err... working as in not crashing.  I can't see the majority of serverside messages (such as lua errors)

**Comment by Earu** [comment] 2022-02-16 16:43
Resolved in https://github.com/Metastruct/gm_enginespew/commit/5022f4f363377c7cef19bf87a48f948902c23830

**Closed as completed by Earu** 2022-02-16 16:43 UTC

**Comment by Fasteroid** [comment] 2022-02-25 19:42
God why... I should have tested this completely, I can't see lua errors from the server now
